export const individualProducts = [
  {
    slug: 'motor-insurance',
    name: 'Motor Insurance',
    shortDesc: 'Comprehensive and third-party cover for your vehicle',
    description: 'Protect your vehicle against accidents, theft, fire, and third-party liabilities. Whether you drive a personal car, SUV, or commercial vehicle, we have the right motor cover for you.',
    covers: ['Accidental damage to your vehicle', 'Theft and attempted theft', 'Fire damage', 'Third-party bodily injury and property damage', 'Windscreen and accessories cover', 'Towing and recovery costs', 'Personal accident benefits for driver and passengers'],
    whoFor: 'Individual car owners, fleet owners, PSV operators, and anyone who owns or drives a vehicle in Kenya.',
    underwriter: 'First Assurance, Britam, Jubilee, CIC, APA',
    icon: 'car',
    image: '/products/motor-insurance.jpg',
  },
  {
    slug: 'first-med',
    name: 'Medical Insurance (First-Med)',
    shortDesc: 'Quality healthcare for you and your family',
    description: 'First-Med by First Assurance gives you access to quality healthcare across Kenya. Cover includes inpatient, outpatient, dental, optical, and maternity benefits.',
    covers: ['Inpatient hospitalisation', 'Outpatient consultations', 'Dental and optical care', 'Maternity benefits', 'Pre-existing conditions (after waiting period)', 'Emergency evacuation', 'Chronic disease management'],
    whoFor: 'Individuals and families looking for comprehensive medical cover in Kenya.',
    underwriter: 'First Assurance (Absa Group)',
    icon: 'heart-pulse',
    image: '/products/medical-insurance.jpg',
  },
  {
    slug: 'home-insurance',
    name: 'Home Insurance (Domestic Package)',
    shortDesc: 'Protect your home and everything in it',
    description: 'Comprehensive domestic package insurance that covers your building, contents, and personal possessions against fire, theft, flood, and other perils.',
    covers: ['Building structure damage', 'Household contents and personal effects', 'Theft and burglary', 'Fire and lightning', 'Flood and storm damage', 'Employer liability for domestic workers', 'Temporary accommodation if home is uninhabitable'],
    whoFor: 'Homeowners, tenants, and landlords in Kenya.',
    underwriter: 'First Assurance, Britam, CIC',
    icon: 'home',
    image: '/products/home-insurance.jpg',
  },
  {
    slug: 'travel-insurance',
    name: 'Travel Insurance',
    shortDesc: 'Travel with peace of mind, anywhere in the world',
    description: 'Whether travelling for business or leisure, protect yourself against medical emergencies, trip cancellations, lost luggage, and more.',
    covers: ['Emergency medical expenses abroad', 'Trip cancellation and curtailment', 'Lost or delayed baggage', 'Travel delay compensation', 'Personal liability', 'Emergency evacuation and repatriation', 'Passport and travel document loss'],
    whoFor: 'Individual travellers, families, business travellers, and students studying abroad.',
    underwriter: 'First Assurance, Jubilee, APA',
    icon: 'plane',
    image: '/products/travel-insurance.jpg',
  },
  {
    slug: 'personal-accident',
    name: 'Personal Accident',
    shortDesc: 'Financial protection against accidental injury or death',
    description: 'Personal accident insurance provides a lump sum payment in the event of accidental death, permanent disability, or temporary disability.',
    covers: ['Accidental death benefit', 'Permanent total disability', 'Permanent partial disability', 'Temporary total disability', 'Medical expenses arising from accident', 'Funeral expenses'],
    whoFor: 'Anyone who wants financial protection against unexpected accidents, including workers, business owners, and students.',
    underwriter: 'First Assurance, Britam, CIC',
    icon: 'shield-check',
  },
  {
    slug: 'golfers-insurance',
    name: 'Golfers Insurance',
    shortDesc: 'Specialised cover for golf enthusiasts',
    description: 'Comprehensive insurance for golfers covering equipment, personal liability on the course, and the famous hole-in-one celebration benefit.',
    covers: ['Golf equipment loss or damage', 'Personal liability on the course', 'Personal accident during play', 'Hole-in-one celebration benefit', 'Loss of green fees due to illness', 'Caddie injury cover'],
    whoFor: 'Amateur and professional golfers, golf club members.',
    underwriter: 'First Assurance',
    icon: 'target',
  },
  {
    slug: 'pvt-insurance',
    name: 'Political Violence & Terrorism',
    shortDesc: 'Cover against political unrest and terrorism risks',
    description: 'Protect your assets against losses caused by political violence, terrorism, strikes, riots, and civil commotion.',
    covers: ['Terrorism and sabotage', 'Political violence and insurrection', 'Strikes, riots, and civil commotion', 'Property damage', 'Business interruption', 'Loss of revenue'],
    whoFor: 'Property owners, businesses, and organisations operating in areas prone to political instability.',
    underwriter: 'First Assurance, Britam',
    icon: 'shield-alert',
  },
  {
    slug: 'icpak-professional-indemnity',
    name: 'ICPAK Professional Indemnity',
    shortDesc: 'Tailored PI cover for accountants and auditors',
    description: 'Professional indemnity insurance designed specifically for ICPAK members, covering claims arising from professional negligence, errors, and omissions.',
    covers: ['Professional negligence claims', 'Errors and omissions', 'Legal defence costs', 'Breach of duty', 'Defamation arising from professional work', 'Loss of documents'],
    whoFor: 'Certified Public Accountants, auditors, and ICPAK members.',
    underwriter: 'First Assurance',
    icon: 'briefcase',
  },
  {
    slug: 'icpak-motor-private',
    name: 'ICPAK Motor Private',
    shortDesc: 'Special motor rates for ICPAK members',
    description: 'Exclusive motor insurance rates negotiated for ICPAK members. Comprehensive cover at preferential premiums.',
    covers: ['All standard motor comprehensive benefits', 'Preferential premium rates for ICPAK members', 'Windscreen cover', 'Personal accident for driver', 'Third-party liability', 'Towing and recovery'],
    whoFor: 'ICPAK members who own private vehicles.',
    underwriter: 'First Assurance',
    icon: 'car',
  },
];

export const corporateProducts = [
  {
    slug: 'group-medical',
    name: 'Group Medical',
    shortDesc: 'Healthcare cover for your employees',
    description: 'Provide quality healthcare to your workforce with group medical insurance. Flexible plans for companies of all sizes with inpatient, outpatient, dental, and optical benefits.',
    covers: ['Inpatient and outpatient cover', 'Dental and optical benefits', 'Maternity cover', 'Chronic disease management', 'Emergency evacuation', 'Pre-existing conditions (with terms)', 'Wellness programmes'],
    whoFor: 'Employers of all sizes looking to provide health benefits to their staff.',
    underwriter: 'First Assurance, Britam, Jubilee, AAR, Madison',
    icon: 'users',
  },
  {
    slug: 'first-afya-biashara',
    name: 'First Afya Biashara',
    shortDesc: 'Affordable medical cover for SMEs',
    description: 'First Afya Biashara by First Assurance is designed for small businesses that want quality medical cover for their team at affordable rates. From as few as 3 members.',
    covers: ['Inpatient hospitalisation', 'Outpatient consultations', 'Dental care', 'Optical care', 'Maternity benefits', 'Last expense benefit'],
    whoFor: 'Small and medium enterprises (SMEs) with 3 or more employees.',
    underwriter: 'First Assurance (Absa Group)',
    icon: 'heart-handshake',
    image: '/products/medical-teams.jpg',
  },
  {
    slug: 'sme-package',
    name: 'SME Package',
    image: '/products/business-insurance.jpg',
    shortDesc: 'All-in-one business protection for SMEs',
    description: 'A bundled insurance package covering fire, theft, burglary, WIBA, and public liability. Everything a small business needs in one policy.',
    covers: ['Fire and allied perils', 'Burglary and theft', 'Work Injury Benefits (WIBA)', 'Public liability', 'Electronic equipment', 'Money in transit', 'Goods in transit', 'Fidelity guarantee'],
    whoFor: 'Small and medium businesses, shops, restaurants, offices, and workshops.',
    underwriter: 'First Assurance, CIC, Britam',
    icon: 'building-2',
  },
  {
    slug: 'engineering-insurance',
    name: 'Engineering Insurance',
    shortDesc: 'Cover for construction and engineering projects',
    description: 'Protect your engineering and construction projects against damage, loss, and third-party liability during construction and operation.',
    covers: ['Contractors all risks (CAR)', 'Erection all risks (EAR)', 'Machinery breakdown', 'Electronic equipment', 'Boiler and pressure vessel', 'Construction plant and equipment', 'Third-party liability during construction'],
    whoFor: 'Contractors, developers, engineers, and project owners.',
    underwriter: 'First Assurance, Jubilee, ICEA Lion',
    icon: 'hard-hat',
  },
  {
    slug: 'marine-insurance',
    name: 'Marine Insurance',
    shortDesc: 'Protect goods in transit by sea, air, or road',
    description: 'Marine cargo insurance covers your goods against loss or damage during transit by sea, air, road, or rail, both locally and internationally.',
    covers: ['Marine cargo (import and export)', 'Inland transit', 'Warehouse to warehouse cover', 'All risks or named perils', 'War and strikes cover', 'General average contribution'],
    whoFor: 'Importers, exporters, manufacturers, and logistics companies.',
    underwriter: 'First Assurance, Jubilee, ICEA Lion',
    icon: 'ship',
  },
  {
    slug: 'goods-in-transit',
    name: 'Goods in Transit',
    shortDesc: 'Cover for goods being transported by road',
    description: 'Protect your goods against loss or damage while being transported by road within Kenya or across East Africa.',
    covers: ['Damage during loading and unloading', 'Accident damage during transit', 'Theft during transit', 'Overturning of vehicle', 'Fire damage', 'Rain and flood damage during transit'],
    whoFor: 'Transport companies, distributors, wholesalers, and any business that moves goods.',
    underwriter: 'First Assurance, CIC, APA',
    icon: 'truck',
  },
  {
    slug: 'fire-insurance',
    name: 'Fire Insurance',
    shortDesc: 'Protect your property against fire and allied perils',
    description: 'Fire and allied perils insurance covers your buildings, stocks, and contents against fire, lightning, explosion, and natural disasters.',
    covers: ['Fire and lightning', 'Explosion', 'Aircraft impact', 'Storm and flood', 'Earthquake', 'Burst pipes', 'Impact by vehicles', 'Malicious damage', 'Loss of rent'],
    whoFor: 'Property owners, landlords, businesses, and tenants with valuable assets.',
    underwriter: 'First Assurance, Britam, Jubilee, CIC',
    icon: 'flame',
  },
  {
    slug: 'liabilities-insurance',
    name: 'Liabilities Insurance',
    shortDesc: 'Protection against legal liability claims',
    description: 'Cover your business against legal liability for injury to third parties, damage to their property, or financial loss caused by your operations.',
    covers: ['Public liability', 'Product liability', 'Employers liability', 'Professional indemnity', 'Directors and officers liability', 'Legal defence costs', 'Compensation awards'],
    whoFor: 'Businesses, manufacturers, service providers, and professionals.',
    underwriter: 'First Assurance, Jubilee, ICEA Lion',
    icon: 'scale',
  },
  {
    slug: 'corporate-travel',
    name: 'Corporate Travel',
    shortDesc: 'Group travel cover for business trips',
    description: 'Comprehensive travel insurance for your employees on business trips, covering medical emergencies, trip cancellations, and more.',
    covers: ['Emergency medical treatment abroad', 'Trip cancellation', 'Lost baggage and personal effects', 'Travel delay', 'Personal liability', 'Emergency evacuation', 'Hijack and kidnap cover'],
    whoFor: 'Companies with employees who travel frequently for business.',
    underwriter: 'First Assurance, Jubilee',
    icon: 'plane',
  },
  {
    slug: 'bima-taasisi',
    name: 'Bima Taasisi',
    shortDesc: 'Insurance package for institutions and SACCOs',
    description: 'Bima Taasisi is a bundled insurance solution for institutions, SACCOs, and cooperatives, covering property, fidelity, and members.',
    covers: ['Fire and allied perils', 'Burglary', 'Fidelity guarantee', 'Money insurance', 'Public liability', 'Group personal accident', 'Electronic equipment'],
    whoFor: 'SACCOs, cooperatives, churches, schools, and other institutions.',
    underwriter: 'First Assurance',
    icon: 'landmark',
  },
  {
    slug: 'wiba',
    name: 'WIBA (Work Injury Benefits)',
    shortDesc: 'Mandatory cover for employee workplace injuries',
    description: 'Work Injury Benefits Act (WIBA) insurance is mandatory for all employers in Kenya. It covers employees against injury, disease, or death arising from their work.',
    covers: ['Death benefit', 'Permanent total disability', 'Permanent partial disability', 'Temporary total disability', 'Medical expenses from work injury', 'Occupational diseases'],
    whoFor: 'All employers in Kenya. WIBA cover is mandatory under the Work Injury Benefits Act.',
    underwriter: 'First Assurance, Britam, CIC, APA',
    icon: 'hard-hat',
  },
  {
    slug: 'professional-indemnity',
    name: 'Professional Indemnity',
    image: '/products/professional-indemnity.jpg',
    shortDesc: 'Cover against professional negligence claims',
    description: 'Protect yourself and your business against claims of professional negligence, errors, omissions, and breach of professional duty.',
    covers: ['Professional negligence', 'Errors and omissions', 'Breach of professional duty', 'Defamation from professional work', 'Loss of client documents', 'Legal defence costs', 'Court awards and settlements'],
    whoFor: 'Lawyers, accountants, architects, engineers, doctors, consultants, and other professionals.',
    underwriter: 'First Assurance, Jubilee, ICEA Lion',
    icon: 'briefcase',
  },
];

export const allProducts = [...individualProducts, ...corporateProducts];
